version: "3.8"
services:
# ####################################################################################   Launch eulator and appium instance
  Android-Service:
    image: amrka/ultimate-android
    build: .
    ports:
      - 4725:4725 ##FOR APPIUM SERVER, OR CHANGE IT TO ANYTHING ELSE
    container_name: Android-Service
    environment:
      APPIUM_PORT: 4725
    privileged: true
    command:
       bash -c './start_emu_headless.sh && ./start_appium.sh'
    tty: true
    stdin_open: true
###################################################################################   Clone you github repository and run script (JAVA/JS)
  Clone-Service:
    image: amrka/ultimate-android
    build: .
    ports:
      - 4700:4700
    container_name: Clone-Service
    environment:
      BRANCH: main                                                                     ##REPO BRANCH NAME
      GITHUB_USERNAME: amrkamel1                                                         ##Github Username
      GITHUB_TOKEN: ghp_wZIj4X7WtvB6xBm                                                  ##Github token
      REPO_NAME:  swypeApp-automation                                                    ##Github repo exact name
      TEST_SCRIPT: 'mvn test'
    privileged: true
    command:
       bash -c './clone_repo.sh && ./execute_test.sh'                            ##  Repo will be clones and test will be exected based on TEST_SCRIPT value
    tty: true
    stdin_open: true
# ####################################################################################   Start selenium instance
  Selenium-Service:
    image: amrka/ultimate-android
    build: .
    ports:
      - 4444:4444                                 ##FOR SELENIUM SERVER  
    container_name: Selenium-Service
    environment: 
      BROWSER: 'firefox'                            ## IF empty chrome browser will be the default, otherwise use firefox 
    command:
      bash -c './start_selenium.sh'           ##STARTING SELENIUM SERVER
    tty: true
    stdin_open: true
# ####################################################################################   Start VNC sever so you can have remote access to the docker machine in VNC ui
  VNC-Service:
    image: amrka/ultimate-android
    build: .
    ports:
      - 5900:5900                               ##FOR VNC SERVER
    container_name: VNC-Service
    environment: 
      VNC_PASSWORD: Test123!!
    privileged: true
    command:
      bash -c './bootstrap.sh'                ##STARTING VNC SERVER
    tty: true
    stdin_open: true
